"""empty message

<<<<<<<< HEAD:migrations/versions/4424806080a6_.py
Revision ID: 4424806080a6
Revises: 
Create Date: 2025-04-02 14:20:19.214899
========
Revision ID: e1c0d336317e
Revises: 
Create Date: 2025-03-31 18:45:01.001034
>>>>>>>> develop:migrations/versions/e1c0d336317e_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/4424806080a6_.py
revision = '4424806080a6'
========
revision = 'e1c0d336317e'
>>>>>>>> develop:migrations/versions/e1c0d336317e_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'non_binary', 'other', name='gender'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.Column('biography', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('budget_currency', sa.String(), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'finished', 'ongoing', 'cancelled', name='status'), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorization', sa.Enum('approved', 'declined', 'pending', 'cancelled', 'removed', name='authorization'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travelers')
    op.drop_table('favorites')
    op.drop_table('trips')
    op.drop_table('notifications')
    op.drop_table('users')
    # ### end Alembic commands ###
