"""empty message

Revision ID: e8add0c5d448
Revises: 2a256a3d698b
Create Date: 2025-03-20 13:59:44.104730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8add0c5d448'
down_revision = '2a256a3d698b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('please specify', 'male', 'female', 'non_binary', 'other', name='gender'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('please specify', 'male', 'female', 'non_binary', 'other', name='gender'),
               nullable=False)

    # ### end Alembic commands ###
